# Generated by Django 4.2.16 on 2024-11-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("id_book", models.AutoField(primary_key=True, serialize=False)),
                ("book_title", models.CharField(max_length=100)),
                ("editorial", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=40)),
                ("user_email", models.EmailField(max_length=255)),
                ("user_password", models.CharField(max_length=255)),
                ("user_age", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserBooks",
            fields=[
                ("id_user_book", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_books",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.books",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.users",
                    ),
                ),
            ],
            options={
                "unique_together": {("id_user", "id_books")},
            },
        ),
    ]
