# Generated by Django 4.2.16 on 2024-11-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
        migrations.AlterModelOptions(
            name="userbooks",
            options={"verbose_name": "User book", "verbose_name_plural": "User books"},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="books",
            name="book_title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="books",
            name="editorial",
            field=models.CharField(max_length=100, verbose_name="Editorial"),
        ),
        migrations.AlterField(
            model_name="books",
            name="id_book",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="books",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published at"
            ),
        ),
        migrations.AlterField(
            model_name="userbooks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="userbooks",
            name="id_books",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.books",
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="userbooks",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.users",
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="userbooks",
            name="id_user_book",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="users",
            name="id_user",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_age",
            field=models.IntegerField(verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_name",
            field=models.CharField(max_length=40, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
    ]
